---
# handlers file for roles/arch
- name: Apache
  service: 
    name: apache 
    state: reloaded

- name: restart php7-fpm
  service: 
    name: php7.1-fpm 
    enabled: yes 
    state: restarted
  become: yes